package api_translate_text;

/**
 *
 * @author Dũng Sobin
 */
public enum Languages {
    Language(""),
    Afrikaans("af"),
    Albanian("sq"),
    Amharic("am"),
    Arabic("ar"),
    Armenian("hy"),
    Azerbaijani("az"),
    Basque("eu"),
    Belarusian("be"),
    Bengali("bn"),
    Bosnian("bs"),
    Bulgarian("bg"),
    Catalan("ca"),
    Cebuano("ceb"),
    Chinese_Simplified("zh-CN"),
    Chinese_Traditional("zh-TW"),
    Corsican("co"),
    Croatian("hr"),
    Czech("cs"),
    Danish("da"),
    Dutch("nl"),
    English("en"),
    Esperanto("eo"),
    Estonian("et"),
    Finnish("fi"),
    French("fr"),
    Frisian("fy"),
    Galician("gl"),
    Georgian("ka"),
    German("de"),
    Greek("el"),
    Gujarati("gu"),
    HaitianCreole("ht"),
    Hausa("ha"),
    Hawaiian("haw"),
    Hebrew("he"),
    Hindi("hi"),
    Hmong("hmn"),
    Hungarian("hu"),
    Icelandic("is"),
    Igbo("ig"),
    Indonesian("id"),
    Irish("ga"),
    Italian("it"),
    Japanese("ja"),
    Javanese("jv"),
    Kannada("kn"),
    Kazakh("kk"),
    Khmer("km"),
    Kinyarwanda("rw"),
    Korean("ko"),
    Kurdish("ku"),
    Kyrgyz("ky"),
    Lao("lo"),
    Latvian("lv"),
    Lithuanian("lt"),
    Luxembourgish("lb"),
    Macedonian("mk"),
    Malagasy("mg"),
    Malay("ms"),
    Malayalam("ml"),
    Maltese("mt"),
    Maori("mi"),
    Marathi("mr"),
    Mongolian("mn"),
    Myanmar("my"),
    Nepali("ne"),
    Norwegian("no"),
    Nyanja("ny"),
    Odia("or"),
    Pashto("ps"),
    Persian("fa"),
    Polish("pl"),
    Portuguese("pt"),
    Punjabi("pa"),
    Romanian("ro"),
    Russian("ru"),
    Samoan("sm"),
    ScotsGaelic("gd"),
    Serbian("sr"),
    Sesotho("st"),
    Shona("sn"),
    Sindhi("sd"),
    Sinhala("si"),
    Slovak("sk"),
    Slovenian("sl"),
    Somali("so"),
    Spanish("es"),
    Sundanese("su"),
    Swahili("sw"),
    Swedish("sv"),
    Tagalog("tl"),
    Tajik("tg"),
    Tamil("ta"),
    Tatar("tt"),
    Telugu("te"),
    Thai("th"),
    Turkish("tr"),
    Turkmen("tk"),
    Ukrainian("uk"),
    Urdu("ur"),
    Uyghur("ug"),
    Uzbek("uz"),
    Vietnamese("vi"),
    Welsh("cy"),
    Xhosa("xh"),
    Yiddish("yi"),
    Yoruba("yo"),
    Zulu("zu");

    private String code;

    private Languages(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
